using System.Text.Json; using backend.Data; using backend.Extensions; using backend.Models; using backend.Security; using backend.Services; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace backend.Controllers;
[ApiController,Authorize,Route("api/customers/{customerId:int}/financial"),Tags("Customer Financials")]
public class FinancialController(CrmDbContext db,IFinancialService financial) : ControllerBase
{
 [HttpGet("summary")] public async Task<ActionResult> Summary(int customerId){var c=await db.Customers.FindAsync(customerId);if(c is null)return NotFound();if(User.IsInRole("SalesExecutive")&&c.AssignedToId!=User.UserId())return Forbid();return Ok(await financial.SummaryAsync(customerId));}
 [HttpGet("history")] public async Task<ActionResult> History(int customerId){var c=await db.Customers.FindAsync(customerId);if(c is null)return NotFound();if(User.IsInRole("SalesExecutive")&&c.AssignedToId!=User.UserId())return Forbid();var agreement=await db.FinancialAgreements.Include(x=>x.Installments).SingleOrDefaultAsync(x=>x.CustomerId==customerId);var payments=await db.Payments.Where(x=>x.CustomerId==customerId).OrderByDescending(x=>x.CreatedAt).Select(x=>new{x.Id,x.Amount,x.PaymentDate,x.Method,x.TransactionReference,x.ProofUrl,x.Status,x.IsReversed,x.ReversalReason,x.CreatedAt}).ToListAsync();var audit=await db.FinancialAuditLogs.Where(x=>x.CustomerId==customerId).OrderByDescending(x=>x.CreatedAt).Select(x=>new{x.Action,x.DetailsJson,x.PerformedById,x.CreatedAt}).ToListAsync();return Ok(new{agreement,installments=agreement==null?new List<EmiInstallment>():agreement.Installments.OrderBy(x=>x.InstallmentNumber).ToList(),payments,audit});}
 [HttpPut("agreement"),RequirePermission(PermissionCodes.AgreementsManage)] public async Task<ActionResult> Agreement(int customerId,AgreementRequest r){if(r.TotalAgreedAmount<=0||r.BookingAmount<0||r.BookingAmount>r.TotalAgreedAmount)return BadRequest(new{message="Agreement amounts are invalid."});if(r.PaymentPlan==PaymentPlanType.Emi&&(r.EmiStartDate is null||r.MonthlyEmiAmount is null or <=0||r.InstallmentCount is null or <=0))return BadRequest(new{message="EMI start date, monthly amount and installment count are required."});var c=await db.Customers.FindAsync(customerId);if(c is null)return NotFound();await using var tx=await db.Database.BeginTransactionAsync();var a=await db.FinancialAgreements.Include(x=>x.Installments).SingleOrDefaultAsync(x=>x.CustomerId==customerId);var action=a is null?FinancialAuditAction.AgreementCreated:FinancialAuditAction.AgreementUpdated;if(a is null){a=new FinancialAgreement{CustomerId=customerId,CreatedById=User.UserId(),UpdatedById=User.UserId()};db.Add(a);}a.TotalAgreedAmount=r.TotalAgreedAmount;a.BookingAmount=r.BookingAmount;a.PaymentPlan=r.PaymentPlan;a.EmiStartDate=r.EmiStartDate?.Date;a.MonthlyEmiAmount=r.MonthlyEmiAmount;a.InstallmentCount=r.InstallmentCount;a.Remarks=r.Remarks;a.UpdatedById=User.UserId();a.UpdatedAt=DateTime.UtcNow;if(a.Installments.Count>0&&!await db.Payments.AnyAsync(x=>x.CustomerId==customerId&&x.Status==PaymentStatus.Approved))db.EmiInstallments.RemoveRange(a.Installments);else if(a.Installments.Count>0)return Conflict(new{message="An agreement with payment history cannot regenerate its schedule."});if(r.PaymentPlan==PaymentPlanType.Emi){decimal remaining=r.TotalAgreedAmount-r.BookingAmount;for(var n=1;n<=r.InstallmentCount!.Value&&remaining>0;n++){var amount=Math.Min(r.MonthlyEmiAmount!.Value,remaining);a.Installments.Add(new EmiInstallment{InstallmentNumber=n,DueDate=r.EmiStartDate!.Value.Date.AddMonths(n-1),ExpectedAmount=amount,Status=InstallmentStatus.Upcoming});remaining-=amount;}if(remaining>0)return BadRequest(new{message="EMI duration and amount do not cover the agreed balance."});}else a.Installments.Add(new EmiInstallment{InstallmentNumber=1,DueDate=r.EmiStartDate?.Date??DateTime.UtcNow.Date,ExpectedAmount=r.TotalAgreedAmount-r.BookingAmount,Status=InstallmentStatus.Upcoming});db.FinancialAuditLogs.Add(new FinancialAuditLog{CustomerId=customerId,Action=action,DetailsJson=JsonSerializer.Serialize(r),PerformedById=User.UserId()});await db.SaveChangesAsync();await tx.CommitAsync();return Ok(await financial.SummaryAsync(customerId));}
 public record AgreementRequest(decimal TotalAgreedAmount,decimal BookingAmount,PaymentPlanType PaymentPlan,DateTime? EmiStartDate,decimal? MonthlyEmiAmount,int? InstallmentCount,string? Remarks);
}
