using backend.Data; using backend.Models; using Microsoft.EntityFrameworkCore;
namespace backend.Services;
public record FinancialSummary(decimal TotalAgreedAmount, decimal TotalPaid, decimal CurrentDue, decimal OverdueAmount, decimal OutstandingBalance, decimal? NextEmiAmount, DateTime? NextEmiDueDate, string PaymentStatus);
public interface IFinancialService { Task<FinancialSummary> SummaryAsync(int customerId, DateTime? asOf=null); Task RecalculateInstallmentsAsync(int agreementId); }
public class FinancialService(CrmDbContext db) : IFinancialService
{
 public async Task<FinancialSummary> SummaryAsync(int customerId, DateTime? asOf=null) { var now=(asOf??DateTime.UtcNow).Date; var agreement=await db.FinancialAgreements.Include(x=>x.Installments).SingleOrDefaultAsync(x=>x.CustomerId==customerId); if(agreement is null)return new(0,0,0,0,0,null,null,"Not configured"); var paid=await db.Payments.Where(x=>x.CustomerId==customerId&&x.Status==PaymentStatus.Approved&&!x.IsReversed).SumAsync(x=>(decimal?)x.Amount)??0; var installments=agreement.Installments; foreach(var i in installments){var remaining=Math.Max(0,i.ExpectedAmount-i.PaidAmount);i.Status=remaining==0?InstallmentStatus.Paid:i.PaidAmount>0?InstallmentStatus.PartiallyPaid:i.DueDate.Date<now?InstallmentStatus.Overdue:i.DueDate.Date==now?InstallmentStatus.Due:InstallmentStatus.Upcoming;} var overdue=installments.Where(x=>x.DueDate.Date<now).Sum(x=>Math.Max(0,x.ExpectedAmount-x.PaidAmount)); var currentDue=installments.Where(x=>x.DueDate.Date<=now).Sum(x=>Math.Max(0,x.ExpectedAmount-x.PaidAmount)); var next=installments.Where(x=>x.DueDate.Date>now&&x.ExpectedAmount>x.PaidAmount).OrderBy(x=>x.DueDate).FirstOrDefault(); var outstanding=Math.Max(0,agreement.TotalAgreedAmount-paid); var status=outstanding==0?"Paid":overdue>0?"Overdue":currentDue>0?"Due":"Upcoming"; return new(agreement.TotalAgreedAmount,paid,currentDue,overdue,outstanding,next is null?null:next.ExpectedAmount-next.PaidAmount,next?.DueDate,status); }
 public async Task RecalculateInstallmentsAsync(int agreementId) { var agreement=await db.FinancialAgreements.Include(x=>x.Installments).SingleAsync(x=>x.Id==agreementId); var payments=await db.Payments.Where(x=>x.CustomerId==agreement.CustomerId&&x.Status==PaymentStatus.Approved&&!x.IsReversed).OrderBy(x=>x.PaymentDate).ThenBy(x=>x.CreatedAt).ToListAsync(); foreach(var i in agreement.Installments){i.PaidAmount=0;i.PaidAt=null;} foreach(var p in payments){if(p.Purpose is PaymentPurpose.BookingAmount or PaymentPurpose.DownPayment or PaymentPurpose.Other)continue;FinancialRules.AllocateOldest(agreement.Installments,p.Amount,p.PaymentDate);} foreach(var i in agreement.Installments)i.Status=FinancialRules.Status(i.ExpectedAmount,i.PaidAmount,i.DueDate,DateTime.UtcNow);await db.SaveChangesAsync(); }
}
