using backend.Data;
using backend.Models;
using Microsoft.EntityFrameworkCore;

namespace backend.Services;

public record ReportRow(Dictionary<string, object?> Values);
public record ReportSeries(string Label, decimal Value);
public record OperationalReportResult(string Key, string Title, string Description, string Source, IReadOnlyList<string> Columns, IReadOnlyList<ReportRow> Rows, IReadOnlyList<ReportSeries> Series, Dictionary<string, decimal> Summary, string? Limitation = null);
public interface IOperationalReportService { Task<OperationalReportResult?> BuildAsync(string key, ReportingFilter filter); }

public sealed class OperationalReportService(CrmDbContext db) : IOperationalReportService
{
    private sealed record LeadRecord(int Id,string CustomerName,string Phone,string? Email,LeadStatus Status,LeadPriority Priority,LeadSource Source,string? BudgetRange,string? PreferredLocation,string? ReferrerName,int? PreviousCustomerId,DateTime CreatedAt,DateTime? AssignedAt,DateTime? LastFollowUpAt,DateTime? NextFollowUpAt,int AssignmentReminderCount,string Project,string Employee,string Creator);
    private static readonly LeadStatus[] Active = [LeadStatus.New,LeadStatus.Assigned,LeadStatus.Contacted,LeadStatus.Interested,LeadStatus.FollowUpNeeded,LeadStatus.SiteVisitScheduled,LeadStatus.Visited,LeadStatus.Negotiation];
    public async Task<OperationalReportResult?> BuildAsync(string key, ReportingFilter f)
    {
        var end=f.To.Date.AddDays(1); var now=DateTime.UtcNow;
        var leadQuery=db.Leads.AsNoTracking().Where(x=>x.CreatedAt>=f.From.Date&&x.CreatedAt<end);
        if(f.SalesExecutiveId.HasValue)leadQuery=leadQuery.Where(x=>x.AssignedToId==f.SalesExecutiveId);if(f.ProjectId.HasValue)leadQuery=leadQuery.Where(x=>x.ProjectId==f.ProjectId);if(f.TeamId.HasValue)leadQuery=leadQuery.Where(x=>x.AssignedTo!=null&&x.AssignedTo.SalesTeamId==f.TeamId);if(f.GroupId.HasValue)leadQuery=leadQuery.Where(x=>x.AssignedTo!=null&&x.AssignedTo.SalesTeam!=null&&x.AssignedTo.SalesTeam.SalesGroupId==f.GroupId);if(f.Source.HasValue)leadQuery=leadQuery.Where(x=>x.Source==f.Source);if(f.LeadStatus.HasValue)leadQuery=leadQuery.Where(x=>x.Status==f.LeadStatus);if(f.Priority.HasValue)leadQuery=leadQuery.Where(x=>x.Priority==f.Priority);
        var leads=await leadQuery.Select(x=>new LeadRecord(x.Id,x.CustomerName,x.Phone,x.Email,x.Status,x.Priority,x.Source,x.BudgetRange,x.PreferredLocation,x.ReferrerName,x.PreviousCustomerId,x.CreatedAt,x.AssignedAt,x.LastFollowUpAt,x.NextFollowUpAt,x.AssignmentReminderCount,x.Project==null?"Unspecified":x.Project.Name,x.AssignedTo==null?"Unassigned":x.AssignedTo.FullName,x.CreatedBy.FullName)).ToListAsync();
        if(key.StartsWith("lead-")||key.StartsWith("pipeline-"))return await LeadOrPipeline(key,leads,f,now);
        if(key.StartsWith("followup-"))return await Followups(key,f,end,now);
        if(key.StartsWith("visit-"))return await Visits(key,f,end,now);
        if(key.StartsWith("collection-"))return await Collections(key,f);
        return null;
    }

    private Task<OperationalReportResult> LeadOrPipeline(string key,List<LeadRecord> leads,ReportingFilter f,DateTime now)
    {
        IEnumerable<LeadRecord> selected=leads; string title=Name(key); string description="Lead records matching the selected reporting period and organization filters."; string? limitation=null;
        if(key=="lead-assigned")selected=leads.Where(x=>x.AssignedAt!=null);else if(key=="lead-unassigned")selected=leads.Where(x=>x.AssignedAt==null);else if(key=="lead-newly-assigned")selected=leads.Where(x=>x.AssignedAt>=f.From&&x.AssignedAt<f.To.AddDays(1));else if(key=="lead-no-first-followup")selected=leads.Where(x=>x.LastFollowUpAt==null);else if(key=="lead-inactive")selected=leads.Where(x=>x.LastFollowUpAt==null||x.LastFollowUpAt<now.AddDays(-7));else if(key=="lead-overdue-followup")selected=leads.Where(x=>x.NextFollowUpAt<now);else if(key=="lead-followup-today")selected=leads.Where(x=>x.NextFollowUpAt?.Date==now.Date);else if(key=="lead-future-followup")selected=leads.Where(x=>x.NextFollowUpAt>now);else if(key=="lead-stale")selected=leads.Where(x=>Active.Contains(x.Status)&&(now-x.CreatedAt).TotalDays>14);else if(key=="lead-repeat")selected=leads.Where(x=>x.PreviousCustomerId!=null);else if(key=="lead-referral")selected=leads.Where(x=>x.Source==LeadSource.Referral);else if(key=="lead-lost")selected=leads.Where(x=>x.Status==LeadStatus.Lost);else if(key=="lead-not-interested")selected=leads.Where(x=>x.Status==LeadStatus.NotInterested);
        if(key=="lead-duplicates")selected=leads.GroupBy(x=>x.Phone.Trim()).Where(g=>g.Count()>1).SelectMany(g=>g);
        if(key is "lead-lost-reasons" or "pipeline-expected-value"){selected=[];limitation=key=="lead-lost-reasons"?"A standardized lost-reason field is not stored yet.":"Expected opportunity value and closing probability are not stored; no values are invented.";}
        Func<LeadRecord,string>? group=key switch{"lead-by-status" or "pipeline-funnel" or "pipeline-stage-dropoff"=>(x=>x.Status.ToString()),"lead-by-priority"=>(x=>x.Priority.ToString()),"lead-by-source" or "lead-source-quality" or "lead-source-conversion" or "pipeline-by-source"=>(x=>x.Source.ToString()),"lead-by-project" or "lead-project-interest" or "pipeline-by-project"=>(x=>x.Project),"lead-by-location"=>(x=>x.PreferredLocation??"Unspecified"),"lead-by-budget"=>(x=>x.BudgetRange??"Unspecified"),"lead-by-creator"=>(x=>x.Creator),"lead-by-employee" or "lead-workload" or "pipeline-by-employee"=>(x=>x.Employee),"lead-referrer-contribution"=>(x=>x.ReferrerName??"Unspecified"),"lead-created-date"=>(x=>x.CreatedAt.ToString("yyyy-MM-dd")),"lead-aging"=>(x=>AgeBucket((now-x.CreatedAt).TotalDays)),_=>null};
        if(group!=null){var grouped=selected.GroupBy(group).Select(g=>new ReportSeries(g.Key,g.Count())).OrderByDescending(x=>x.Value).ToList();return Task.FromResult(SummaryReport(key,title,description,grouped,selected.Count(),limitation));}
        if(key.StartsWith("pipeline-")&&key is not "pipeline-register"){var stages=Enum.GetValues<LeadStatus>().Where(s=>s!=LeadStatus.InvoiceGenerated).Select(s=>new ReportSeries(s.ToString(),selected.Count(x=>x.Status==s))).ToList();return Task.FromResult(SummaryReport(key,title,"Pipeline stage distribution and conversion view. Invoice stages are excluded.",stages,selected.Count(),limitation));}
        var rows=selected.Take(5000).Select(x=>Row(("id",x.Id),("name",x.CustomerName),("phone",x.Phone),("status",x.Status.ToString()),("priority",x.Priority.ToString()),("source",x.Source.ToString()),("project",x.Project),("employee",x.Employee),("createdAt",x.CreatedAt),("assignedAt",x.AssignedAt),("lastFollowUpAt",x.LastFollowUpAt),("nextFollowUpAt",x.NextFollowUpAt))).ToList();
        return Task.FromResult(new OperationalReportResult(key,title,description,"CRM leads",rows.FirstOrDefault()?.Values.Keys.ToList()??[],rows,[],new(){{"records",rows.Count}},limitation));
    }

    private async Task<OperationalReportResult> Followups(string key,ReportingFilter f,DateTime end,DateTime now)
    {
        var q=db.FollowUps.AsNoTracking().Where(x=>x.CreatedAt>=f.From.Date&&x.CreatedAt<end);if(f.SalesExecutiveId.HasValue)q=q.Where(x=>x.CreatedById==f.SalesExecutiveId);if(f.ProjectId.HasValue)q=q.Where(x=>x.Lead.ProjectId==f.ProjectId);if(f.TeamId.HasValue)q=q.Where(x=>x.CreatedBy.SalesTeamId==f.TeamId);if(f.GroupId.HasValue)q=q.Where(x=>x.CreatedBy.SalesTeam!=null&&x.CreatedBy.SalesTeam.SalesGroupId==f.GroupId);
        var data=await q.Select(x=>new{x.Id,x.LeadId,Lead=x.Lead.CustomerName,Customer=x.Customer==null?null:x.Customer.Name,Employee=x.CreatedBy.FullName,x.Type,x.ResultingStatus,x.Summary,x.NextFollowUpAt,x.CreatedAt,ProofCount=x.Proofs.Count}).ToListAsync();IEnumerable<dynamic> selected=data;
        if(key=="followup-with-proof")selected=data.Where(x=>x.ProofCount>0);else if(key=="followup-without-proof")selected=data.Where(x=>x.ProofCount==0);else if(key=="followup-overdue"||key=="followup-missed")selected=data.Where(x=>x.NextFollowUpAt<now);else if(key=="followup-next-actions")selected=data.Where(x=>x.NextFollowUpAt>=now);
        Func<dynamic,string>? group=key switch{"followup-by-employee" or "followup-effectiveness-employee"=>(x=>x.Employee),"followup-by-type" or "followup-effectiveness-type" or "followup-activity"=>(x=>x.Type.ToString()),"followup-by-result"=>(x=>x.ResultingStatus?.ToString()??"No change"),"followup-counts"=>(x=>x.CreatedAt.ToString("yyyy-MM-dd")),"followup-proof-distribution"=>(x=>x.ProofCount>0?"With proof":"Without proof"),_=>null};
        if(group!=null){var series=selected.GroupBy(group).Select(g=>new ReportSeries(g.Key,g.Count())).OrderByDescending(x=>x.Value).ToList();return SummaryReport(key,Name(key),"Follow-up activity grouped by the selected dimension.",series,selected.Count());}
        var rows=selected.Take(5000).Select(x=>Row(("id",x.Id),("lead",x.Lead),("customer",x.Customer),("employee",x.Employee),("type",x.Type.ToString()),("result",x.ResultingStatus?.ToString()),("summary",x.Summary),("proofs",x.ProofCount),("createdAt",x.CreatedAt),("nextFollowUpAt",x.NextFollowUpAt))).ToList();return new(key,Name(key),"Follow-up activity records.","CRM follow-ups",rows.FirstOrDefault()?.Values.Keys.ToList()??[],rows,[],new(){{"records",rows.Count},{"withProof",selected.Count(x=>x.ProofCount>0)}},null);
    }

    private async Task<OperationalReportResult> Visits(string key,ReportingFilter f,DateTime end,DateTime now)
    {
        var q=db.VehicleBookings.AsNoTracking().Where(x=>x.CreatedAt>=f.From.Date&&x.CreatedAt<end);if(f.SalesExecutiveId.HasValue)q=q.Where(x=>x.SalesExecutiveId==f.SalesExecutiveId);if(f.ProjectId.HasValue)q=q.Where(x=>x.ProjectId==f.ProjectId);if(f.TeamId.HasValue)q=q.Where(x=>x.SalesExecutive.SalesTeamId==f.TeamId);if(f.GroupId.HasValue)q=q.Where(x=>x.SalesExecutive.SalesTeam!=null&&x.SalesExecutive.SalesTeam.SalesGroupId==f.GroupId);
        var data=await q.Select(x=>new{x.Id,Customer=x.Customer==null?"Legacy":x.Customer.Name,Project=x.Project==null?"Unspecified":x.Project.Name,Employee=x.SalesExecutive.FullName,Vehicle=x.Vehicle==null?"Unassigned":x.Vehicle.RegistrationNumber,x.Driver,x.VisitDate,x.VisitTime,x.PersonCount,x.PickupPlace,x.VisitPlace,x.Status,x.CreatedAt,x.ReviewedAt,x.CancellationReason}).ToListAsync();IEnumerable<dynamic> selected=data;
        if(key=="visit-pending")selected=data.Where(x=>x.Status==VehicleBookingStatus.Pending);else if(key=="visit-approved")selected=data.Where(x=>x.Status==VehicleBookingStatus.Approved);else if(key=="visit-rejected")selected=data.Where(x=>x.Status==VehicleBookingStatus.Rejected);else if(key=="visit-cancelled")selected=data.Where(x=>x.Status==VehicleBookingStatus.Cancelled);else if(key=="visit-upcoming")selected=data.Where(x=>x.VisitDate>=DateOnly.FromDateTime(now));
        if(key is "visit-completed" or "visit-no-show" or "visit-operating-cost")return SummaryReport(key,Name(key),"This report is unavailable until its source data is recorded.",[],0,key=="visit-operating-cost"?"Fuel, maintenance and trip expenses are not stored.":"Completed and no-show visit statuses are not stored.");
        Func<dynamic,string>? group=key switch{"visit-by-project" or "visit-project-popularity"=>(x=>x.Project),"visit-by-customer" or "visit-repeat"=>(x=>x.Customer),"visit-by-employee" or "visit-employee-success"=>(x=>x.Employee),"visit-by-vehicle" or "visit-vehicle-utilization"=>(x=>x.Vehicle),"visit-by-driver"=>(x=>x.Driver??"Unassigned"),"visit-passengers"=>(x=>x.PersonCount.ToString()),"visit-pickup"=>(x=>x.PickupPlace),"visit-cancellation-reasons"=>(x=>x.CancellationReason??"Unspecified"),_=>null};
        if(group!=null){var series=selected.GroupBy(group).Select(g=>new ReportSeries(g.Key,g.Count())).OrderByDescending(x=>x.Value).ToList();return SummaryReport(key,Name(key),"Site-visit activity grouped by the selected dimension.",series,selected.Count());}
        var rows=selected.Take(5000).Select(x=>Row(("id",x.Id),("customer",x.Customer),("project",x.Project),("employee",x.Employee),("visitDate",x.VisitDate),("visitTime",x.VisitTime),("status",x.Status.ToString()),("vehicle",x.Vehicle),("driver",x.Driver),("passengers",x.PersonCount),("pickup",x.PickupPlace),("createdAt",x.CreatedAt))).ToList();return new(key,Name(key),"Site-visit and transportation records.","CRM vehicle bookings",rows.FirstOrDefault()?.Values.Keys.ToList()??[],rows,[],new(){{"records",rows.Count}},null);
    }

    private async Task<OperationalReportResult> Collections(string key,ReportingFilter f)
    {
        var from=new DateOnly(f.From.Year,f.From.Month,1);var to=new DateOnly(f.To.Year,f.To.Month,1);var q=db.MonthlyCollections.AsNoTracking().Where(x=>x.Month>=from&&x.Month<=to);if(f.SalesExecutiveId.HasValue)q=q.Where(x=>x.SalesExecutiveId==f.SalesExecutiveId);if(f.TeamId.HasValue)q=q.Where(x=>x.SalesExecutive.SalesTeamId==f.TeamId);if(f.GroupId.HasValue)q=q.Where(x=>x.SalesExecutive.SalesTeam!=null&&x.SalesExecutive.SalesTeam.SalesGroupId==f.GroupId);
        var data=await q.Select(x=>new{x.Id,x.Month,x.Amount,Employee=x.SalesExecutive.FullName,Team=x.SalesExecutive.SalesTeam==null?"Unassigned":x.SalesExecutive.SalesTeam.Name,Group=x.SalesExecutive.SalesTeam==null?"Unassigned":x.SalesExecutive.SalesTeam.SalesGroup.Name,x.Remarks,RecordedBy=x.RecordedBy.FullName,x.UpdatedAt}).ToListAsync();Func<dynamic,string> group=key switch{"collection-by-employee"=>(x=>x.Employee),"collection-by-team"=>(x=>x.Team),"collection-by-group"=>(x=>x.Group),_=>(x=>x.Month.ToString("yyyy-MM"))};var series=data.GroupBy(group).Select(g=>new ReportSeries(g.Key,g.Sum(x=>(decimal)x.Amount))).OrderByDescending(x=>x.Value).ToList();var rows=data.OrderByDescending(x=>x.Month).Select(x=>Row(("month",x.Month),("employee",x.Employee),("team",x.Team),("group",x.Group),("amount",x.Amount),("remarks",x.Remarks),("recordedBy",x.RecordedBy),("updatedAt",x.UpdatedAt))).ToList();return new(key,Name(key),"Authoritative totals entered by CA per sales employee and month. Customer payments are never included.","CA employee-month collections",rows.FirstOrDefault()?.Values.Keys.ToList()??[],rows,series,new(){{"total",data.Sum(x=>x.Amount)},{"entries",data.Count}},null);
    }

    private static OperationalReportResult SummaryReport(string key,string title,string description,IReadOnlyList<ReportSeries> series,int total,string? limitation=null){var rows=series.Select(x=>Row(("category",x.Label),("value",x.Value))).ToList();return new(key,title,description,"CRM operational data",["category","value"],rows,series,new(){{"records",total}},limitation);}
    private static ReportRow Row(params (string Key,object? Value)[] values)=>new(values.ToDictionary(x=>x.Key,x=>x.Value));
    private static string AgeBucket(double d)=>d<=1?"0–1 days":d<=7?"2–7 days":d<=14?"8–14 days":d<=30?"15–30 days":d<=60?"31–60 days":"61+ days";
    private static string Name(string key)=>System.Globalization.CultureInfo.InvariantCulture.TextInfo.ToTitleCase(key.Replace('-',' '));
}
