using backend.Data;
using backend.Models;
using Microsoft.EntityFrameworkCore;

namespace backend.Services;

public record KpiPoint(DateTime Date, decimal Value);
public record KpiResult(string Key, string Name, decimal CurrentValue, decimal PreviousValue, decimal ChangeAmount, decimal ChangePercentage, decimal Target, decimal AchievementPercentage, string Status, string Unit, IReadOnlyList<KpiPoint> Trend, string DrilldownKey, string Formula, bool IsEstimate = false);
public record ReportingFilter(DateTime From, DateTime To, int? SalesExecutiveId = null, int? ProjectId = null, int? TeamId = null, int? GroupId = null, LeadSource? Source = null, LeadStatus? LeadStatus = null, LeadPriority? Priority = null);

public interface IReportingService { Task<IReadOnlyList<KpiResult>> KpisAsync(ReportingFilter filter); }

public sealed class ReportingService(CrmDbContext db) : IReportingService
{
    private static readonly LeadStatus[] ActiveStatuses = [LeadStatus.New, LeadStatus.Assigned, LeadStatus.Contacted, LeadStatus.Interested, LeadStatus.FollowUpNeeded, LeadStatus.SiteVisitScheduled, LeadStatus.Visited, LeadStatus.Negotiation];

    public async Task<IReadOnlyList<KpiResult>> KpisAsync(ReportingFilter f)
    {
        var from = f.From.Date; var toExclusive = f.To.Date.AddDays(1); var days = Math.Max(1, (toExclusive - from).Days); var previousFrom = from.AddDays(-days); var previousTo = from;
        var leads = db.Leads.AsNoTracking().AsQueryable(); var customers = db.Customers.AsNoTracking().AsQueryable(); var followups = db.FollowUps.AsNoTracking().AsQueryable(); var visits = db.VehicleBookings.AsNoTracking().AsQueryable();
        if (f.SalesExecutiveId.HasValue) { leads = leads.Where(x => x.AssignedToId == f.SalesExecutiveId); customers = customers.Where(x => x.AssignedToId == f.SalesExecutiveId); followups = followups.Where(x => x.CreatedById == f.SalesExecutiveId); visits = visits.Where(x => x.SalesExecutiveId == f.SalesExecutiveId); }
        if (f.ProjectId.HasValue) { leads = leads.Where(x => x.ProjectId == f.ProjectId); customers = customers.Where(x => x.ProjectId == f.ProjectId); visits = visits.Where(x => x.ProjectId == f.ProjectId); }
        if (f.TeamId.HasValue) { leads = leads.Where(x => x.AssignedTo != null && x.AssignedTo.SalesTeamId == f.TeamId); customers = customers.Where(x => x.AssignedTo != null && x.AssignedTo.SalesTeamId == f.TeamId); }
        if (f.GroupId.HasValue) { leads = leads.Where(x => x.AssignedTo != null && x.AssignedTo.SalesTeam != null && x.AssignedTo.SalesTeam.SalesGroupId == f.GroupId); customers = customers.Where(x => x.AssignedTo != null && x.AssignedTo.SalesTeam != null && x.AssignedTo.SalesTeam.SalesGroupId == f.GroupId); }
        if (f.Source.HasValue) leads = leads.Where(x => x.Source == f.Source); if (f.LeadStatus.HasValue) leads = leads.Where(x => x.Status == f.LeadStatus); if (f.Priority.HasValue) leads = leads.Where(x => x.Priority == f.Priority);

        var leadRows = await leads.Select(x => new { x.Id, x.Status, x.AssignedToId, x.AssignedAt, x.CreatedAt, x.LastFollowUpAt, x.NextFollowUpAt, x.PreviousCustomerId, x.ProjectId }).ToListAsync();
        var customerRows = await customers.Select(x => new { x.Id, x.LeadId, x.BookedAt, x.CreatedAt, x.ProjectId }).ToListAsync();
        var followRows = await followups.Select(x => new { x.Id, x.LeadId, x.CreatedAt, x.NextFollowUpAt, ProofCount = x.Proofs.Count }).ToListAsync();
        var visitRows = await visits.Select(x => new { x.Id, x.LeadId, x.CustomerId, x.VehicleId, x.VisitDate, x.Status, x.CreatedAt, x.ReviewedAt }).ToListAsync();
        var monthFrom = new DateOnly(from.Year, from.Month, 1); var monthTo = new DateOnly(f.To.Year, f.To.Month, 1); var prevMonthFrom = new DateOnly(previousFrom.Year, previousFrom.Month, 1); var prevMonthTo = new DateOnly(previousTo.AddDays(-1).Year, previousTo.AddDays(-1).Month, 1);
        var collectionsQuery = db.MonthlyCollections.AsNoTracking().AsQueryable(); var targetsQuery = db.MonthlySalesTargets.AsNoTracking().AsQueryable();
        if (f.SalesExecutiveId.HasValue) { collectionsQuery = collectionsQuery.Where(x => x.SalesExecutiveId == f.SalesExecutiveId); targetsQuery = targetsQuery.Where(x => x.SalesExecutiveId == f.SalesExecutiveId); }
        if (f.TeamId.HasValue) { collectionsQuery = collectionsQuery.Where(x => x.SalesExecutive.SalesTeamId == f.TeamId); targetsQuery = targetsQuery.Where(x => x.SalesExecutive.SalesTeamId == f.TeamId); }
        if (f.GroupId.HasValue) { collectionsQuery = collectionsQuery.Where(x => x.SalesExecutive.SalesTeam != null && x.SalesExecutive.SalesTeam.SalesGroupId == f.GroupId); targetsQuery = targetsQuery.Where(x => x.SalesExecutive.SalesTeam != null && x.SalesExecutive.SalesTeam.SalesGroupId == f.GroupId); }
        var collections = await collectionsQuery.Where(x => x.Month >= prevMonthFrom && x.Month <= monthTo).ToListAsync(); var targets = await targetsQuery.Where(x => x.Month >= prevMonthFrom && x.Month <= monthTo).ToListAsync();
        var agreements = await db.FinancialAgreements.AsNoTracking().Where(x => !f.SalesExecutiveId.HasValue || x.Customer.AssignedToId == f.SalesExecutiveId).Select(x => new { x.TotalAgreedAmount, x.BookingAmount, x.DownPaymentAmount }).ToListAsync();
        var installments = await db.EmiInstallments.AsNoTracking().Where(x => !f.SalesExecutiveId.HasValue || x.FinancialAgreement.Customer.AssignedToId == f.SalesExecutiveId).Select(x => new { x.ExpectedAmount, x.PaidAmount, x.DueDate, x.Status }).ToListAsync();
        var commissions = await db.Commissions.AsNoTracking().Where(x => x.CreatedAt >= previousFrom && x.CreatedAt < toExclusive && x.Status != CommissionStatus.Rejected && (!f.SalesExecutiveId.HasValue || x.SalesExecutiveId == f.SalesExecutiveId)).Select(x => new { x.Amount, x.CreatedAt }).ToListAsync();
        var workReports = await db.DailyWorkReports.AsNoTracking().Where(x => x.WorkDate >= DateOnly.FromDateTime(previousFrom) && x.WorkDate <= DateOnly.FromDateTime(f.To) && (!f.SalesExecutiveId.HasValue || x.SalesExecutiveId == f.SalesExecutiveId)).ToListAsync();

        bool Cur(DateTime d) => d >= from && d < toExclusive; bool Prev(DateTime d) => d >= previousFrom && d < previousTo;
        var curLeads = leadRows.Where(x => Cur(x.CreatedAt)).ToList(); var prevLeads = leadRows.Where(x => Prev(x.CreatedAt)).ToList(); var curCustomers = customerRows.Where(x => x.BookedAt.HasValue && Cur(x.BookedAt.Value)).ToList(); var prevCustomers = customerRows.Where(x => x.BookedAt.HasValue && Prev(x.BookedAt.Value)).ToList();
        var curFollow = followRows.Where(x => Cur(x.CreatedAt)).ToList(); var prevFollow = followRows.Where(x => Prev(x.CreatedAt)).ToList(); var curVisits = visitRows.Where(x => Cur(x.CreatedAt)).ToList(); var prevVisits = visitRows.Where(x => Prev(x.CreatedAt)).ToList();
        decimal curCollection = collections.Where(x => x.Month >= monthFrom && x.Month <= monthTo).Sum(x => x.Amount), prevCollection = collections.Where(x => x.Month >= prevMonthFrom && x.Month <= prevMonthTo).Sum(x => x.Amount); decimal collectionTarget = targets.Where(x => x.Month >= monthFrom && x.Month <= monthTo).Sum(x => x.MinimumCollectionAmount); decimal unitTarget = targets.Where(x => x.Month >= monthFrom && x.Month <= monthTo).Sum(x => x.MinimumSalesUnits);
        var now = DateTime.UtcNow; var totalAgreed = agreements.Sum(x => x.TotalAgreedAmount); var installmentOutstanding = installments.Sum(x => Math.Max(0, x.ExpectedAmount - x.PaidAmount)); var overdue = installments.Where(x => x.DueDate.Date < now.Date && x.PaidAmount < x.ExpectedAmount).Sum(x => x.ExpectedAmount - x.PaidAmount);
        var curContacted = curLeads.Count(x => (int)x.Status >= (int)LeadStatus.Contacted && x.Status != LeadStatus.NotInterested); var prevContacted = prevLeads.Count(x => (int)x.Status >= (int)LeadStatus.Contacted && x.Status != LeadStatus.NotInterested); var curInterested = curLeads.Count(x => (int)x.Status >= (int)LeadStatus.Interested && x.Status != LeadStatus.Lost && x.Status != LeadStatus.NotInterested); var prevInterested = prevLeads.Count(x => (int)x.Status >= (int)LeadStatus.Interested && x.Status != LeadStatus.Lost && x.Status != LeadStatus.NotInterested);
        var curVisitLeads = curVisits.Where(x => x.Status == VehicleBookingStatus.Approved).Select(x => x.LeadId).Where(x => x.HasValue).Distinct().Count(); var prevVisitLeads = prevVisits.Where(x => x.Status == VehicleBookingStatus.Approved).Select(x => x.LeadId).Where(x => x.HasValue).Distinct().Count();
        var curLost = curLeads.Count(x => x.Status is LeadStatus.Lost or LeadStatus.NotInterested); var prevLost = prevLeads.Count(x => x.Status is LeadStatus.Lost or LeadStatus.NotInterested); var curAssigned = curLeads.Count(x => x.AssignedToId.HasValue); var prevAssigned = prevLeads.Count(x => x.AssignedToId.HasValue);
        var curFirstSla = curLeads.Count(x => x.AssignedAt.HasValue && x.LastFollowUpAt.HasValue && (x.LastFollowUpAt.Value - x.AssignedAt.Value).TotalHours <= 24); var prevFirstSla = prevLeads.Count(x => x.AssignedAt.HasValue && x.LastFollowUpAt.HasValue && (x.LastFollowUpAt.Value - x.AssignedAt.Value).TotalHours <= 24);
        var curDueFollow = leadRows.Count(x => x.NextFollowUpAt >= from && x.NextFollowUpAt < toExclusive); var prevDueFollow = leadRows.Count(x => x.NextFollowUpAt >= previousFrom && x.NextFollowUpAt < previousTo); var curOverdueFollow = leadRows.Count(x => x.NextFollowUpAt >= from && x.NextFollowUpAt < toExclusive && x.NextFollowUpAt < now); var prevOverdueFollow = leadRows.Count(x => x.NextFollowUpAt >= previousFrom && x.NextFollowUpAt < previousTo);
        var returns = await db.LeadReturns.AsNoTracking().Where(x => x.ReturnedAt >= previousFrom && x.ReturnedAt < toExclusive && (!f.SalesExecutiveId.HasValue || x.SalesExecutiveId == f.SalesExecutiveId)).Select(x => x.ReturnedAt).ToListAsync();
        var saleDays = curCustomers.Where(c => c.LeadId.HasValue).Select(c => { var l = leadRows.FirstOrDefault(x => x.Id == c.LeadId); return l == null ? 0 : (c.BookedAt!.Value - l.CreatedAt).TotalDays; }).Where(x => x >= 0).ToList(); var prevSaleDays = prevCustomers.Where(c => c.LeadId.HasValue).Select(c => { var l = leadRows.FirstOrDefault(x => x.Id == c.LeadId); return l == null ? 0 : (c.BookedAt!.Value - l.CreatedAt).TotalDays; }).Where(x => x >= 0).ToList();
        var avgBooking = KpiFormulas.Average(agreements.Sum(x => x.TotalAgreedAmount), Math.Max(1, customerRows.Count)); var avgCycle = KpiFormulas.Average((decimal)saleDays.Sum(), saleDays.Count); var winRate = KpiFormulas.Rate(curCustomers.Count, curCustomers.Count + curLost);
        var activeVehicles = await db.Vehicles.CountAsync(x => x.IsActive); var executiveCount = Math.Max(1, await db.Users.CountAsync(x => x.IsActive && x.Role.Name == "SalesExecutive")); var workingDays = Math.Max(1, Enumerable.Range(0, days).Count(i => from.AddDays(i).DayOfWeek is not DayOfWeek.Friday));

        var raw = new List<(string Key,string Name,decimal Cur,decimal Prev,decimal Target,string Unit,string Formula,bool Lower,bool Estimate)>
        {
            ("lead-assignment-rate","Lead assignment rate",KpiFormulas.Rate(curAssigned,curLeads.Count),KpiFormulas.Rate(prevAssigned,prevLeads.Count),95,"%","assigned leads / new leads × 100",false,false),
            ("first-contact-sla","First-contact SLA",KpiFormulas.Rate(curFirstSla,curAssigned),KpiFormulas.Rate(prevFirstSla,prevAssigned),90,"%","assigned leads contacted within 24h / assigned leads × 100",false,false),
            ("follow-up-completion","Follow-up completion rate",KpiFormulas.Rate(curDueFollow-curOverdueFollow,curDueFollow),KpiFormulas.Rate(prevDueFollow-prevOverdueFollow,prevDueFollow),90,"%","completed scheduled follow-ups / scheduled follow-ups × 100",false,true),
            ("overdue-follow-up","Overdue follow-up rate",KpiFormulas.Rate(curOverdueFollow,curDueFollow),KpiFormulas.Rate(prevOverdueFollow,prevDueFollow),10,"%","overdue scheduled follow-ups / scheduled follow-ups × 100",true,false),
            ("lead-return","Lead return rate",KpiFormulas.Rate(returns.Count(Cur),curAssigned),KpiFormulas.Rate(returns.Count(Prev),prevAssigned),5,"%","returned leads / assigned leads × 100",true,false),
            ("lead-contact-conversion","Lead-to-contact conversion",KpiFormulas.Rate(curContacted,curLeads.Count),KpiFormulas.Rate(prevContacted,prevLeads.Count),80,"%","contacted leads / new leads × 100",false,false),
            ("contact-interest-conversion","Contact-to-interest conversion",KpiFormulas.Rate(curInterested,curContacted),KpiFormulas.Rate(prevInterested,prevContacted),50,"%","interested leads / contacted leads × 100",false,false),
            ("interest-visit-conversion","Interest-to-visit conversion",KpiFormulas.Rate(curVisitLeads,curInterested),KpiFormulas.Rate(prevVisitLeads,prevInterested),40,"%","approved visited leads / interested leads × 100",false,false),
            ("visit-booking-conversion","Visit-to-booking conversion",KpiFormulas.Rate(curCustomers.Count,curVisitLeads),KpiFormulas.Rate(prevCustomers.Count,prevVisitLeads),30,"%","bookings / approved visited leads × 100",false,false),
            ("lead-booking-conversion","Overall lead-to-booking conversion",KpiFormulas.Rate(curCustomers.Count,curLeads.Count),KpiFormulas.Rate(prevCustomers.Count,prevLeads.Count),15,"%","bookings / new leads × 100",false,false),
            ("win-rate","Win rate",winRate,KpiFormulas.Rate(prevCustomers.Count,prevCustomers.Count+prevLost),30,"%","bookings / (bookings + lost outcomes) × 100",false,false),
            ("loss-rate","Loss rate",KpiFormulas.Rate(curLost,curCustomers.Count+curLost),KpiFormulas.Rate(prevLost,prevCustomers.Count+prevLost),20,"%","lost outcomes / (bookings + lost outcomes) × 100",true,false),
            ("average-sales-cycle","Average sales-cycle days",avgCycle,KpiFormulas.Average((decimal)prevSaleDays.Sum(),prevSaleDays.Count),30,"days","sum(days lead created to booked) / bookings",true,false),
            ("average-stage-age","Average stage age",KpiFormulas.Average((decimal)leadRows.Where(x=>ActiveStatuses.Contains(x.Status)).Sum(x=>(now-x.CreatedAt).TotalDays),leadRows.Count(x=>ActiveStatuses.Contains(x.Status))),0,14,"days","sum(active lead age) / active leads; stage-history refines this",true,true),
            ("pipeline-velocity","Pipeline velocity",KpiFormulas.PipelineVelocity(leadRows.Count(x=>ActiveStatuses.Contains(x.Status)),winRate,avgBooking,avgCycle),0,0,"BDT/day","active opportunities × win rate × avg booking value / avg sales-cycle days",false,false),
            ("sales-target","Sales target achievement",KpiFormulas.Achievement(curCustomers.Count,unitTarget),KpiFormulas.Achievement(prevCustomers.Count,targets.Where(x=>x.Month>=prevMonthFrom&&x.Month<=prevMonthTo).Sum(x=>x.MinimumSalesUnits)),100,"%","booked units / unit target × 100",false,false),
            ("collection-target","Collection target achievement",KpiFormulas.Achievement(curCollection,collectionTarget),KpiFormulas.Achievement(prevCollection,targets.Where(x=>x.Month>=prevMonthFrom&&x.Month<=prevMonthTo).Sum(x=>x.MinimumCollectionAmount)),100,"%","CA employee-month collection / collection target × 100",false,false),
            ("collection-efficiency","Collection efficiency",KpiFormulas.Rate(curCollection,collectionTarget),KpiFormulas.Rate(prevCollection,targets.Where(x=>x.Month>=prevMonthFrom&&x.Month<=prevMonthTo).Sum(x=>x.MinimumCollectionAmount)),100,"%","CA employee-month collection / expected target × 100",false,false),
            ("outstanding-ratio","Outstanding ratio",KpiFormulas.Rate(installmentOutstanding,totalAgreed),0,20,"%","unpaid scheduled installment value / total agreed value × 100",true,false),
            ("overdue-ratio","Overdue ratio",KpiFormulas.Rate(overdue,installmentOutstanding),0,10,"%","overdue unpaid value / outstanding value × 100",true,false),
            ("emi-default","EMI default rate",KpiFormulas.Rate(installments.Count(x=>x.DueDate.Date<now.Date&&x.PaidAmount<x.ExpectedAmount),installments.Count),0,5,"%","overdue installments / all installments × 100",true,false),
            ("average-collection-booking","Average collection per booking",KpiFormulas.Average(curCollection,curCustomers.Count),KpiFormulas.Average(prevCollection,prevCustomers.Count),0,"BDT","CA employee-month collection / bookings",false,false),
            ("average-booking-value","Average booking value",avgBooking,avgBooking,0,"BDT","total agreed sales value / booked customers",false,false),
            ("commission-collection","Commission-to-collection ratio",KpiFormulas.Rate(commissions.Where(x=>Cur(x.CreatedAt)).Sum(x=>x.Amount),curCollection),KpiFormulas.Rate(commissions.Where(x=>Prev(x.CreatedAt)).Sum(x=>x.Amount),prevCollection),5,"%","valid commissions / CA employee-month collection × 100",true,false),
            ("employee-activity","Employee activity score",(KpiFormulas.Rate(curFollow.Count,Math.Max(1,curLeads.Count))+KpiFormulas.Rate(workReports.Count(x=>x.WorkDate>=DateOnly.FromDateTime(from)),executiveCount*workingDays))/2,0,85,"%","average of follow-up coverage and daily-report compliance",false,false),
            ("follow-up-proof","Follow-up proof compliance",KpiFormulas.Rate(curFollow.Count(x=>x.ProofCount>0),curFollow.Count),KpiFormulas.Rate(prevFollow.Count(x=>x.ProofCount>0),prevFollow.Count),90,"%","follow-ups with proof / follow-ups × 100",false,false),
            ("daily-work-report","Daily work-report compliance",KpiFormulas.Rate(workReports.Count(x=>x.WorkDate>=DateOnly.FromDateTime(from)),executiveCount*workingDays),KpiFormulas.Rate(workReports.Count(x=>x.WorkDate>=DateOnly.FromDateTime(previousFrom)&&x.WorkDate<DateOnly.FromDateTime(previousTo)),executiveCount*workingDays),95,"%","submitted daily reports / expected working-day reports × 100",false,false),
            ("site-visit-utilization","Site-visit utilization",KpiFormulas.Rate(curVisits.Count(x=>x.Status==VehicleBookingStatus.Approved),curVisits.Count),KpiFormulas.Rate(prevVisits.Count(x=>x.Status==VehicleBookingStatus.Approved),prevVisits.Count),80,"%","approved visits / visit requests × 100",false,false),
            ("vehicle-utilization","Vehicle utilization",KpiFormulas.Rate(curVisits.Where(x=>x.Status==VehicleBookingStatus.Approved&&x.VehicleId!=null).Select(x=>x.VehicleId).Distinct().Count(),activeVehicles),KpiFormulas.Rate(prevVisits.Where(x=>x.Status==VehicleBookingStatus.Approved&&x.VehicleId!=null).Select(x=>x.VehicleId).Distinct().Count(),activeVehicles),70,"%","vehicles used / active vehicles × 100",false,false),
            ("repeat-referral","Customer repeat/referral rate",KpiFormulas.Rate(curLeads.Count(x=>x.PreviousCustomerId!=null),curLeads.Count),KpiFormulas.Rate(prevLeads.Count(x=>x.PreviousCustomerId!=null),prevLeads.Count),15,"%","repeat/referral-linked leads / new leads × 100",false,false),
            ("project-conversion","Project conversion rate",KpiFormulas.Rate(curCustomers.Count(x=>x.ProjectId!=null),curLeads.Count(x=>x.ProjectId!=null)),KpiFormulas.Rate(prevCustomers.Count(x=>x.ProjectId!=null),prevLeads.Count(x=>x.ProjectId!=null)),20,"%","project bookings / project leads × 100",false,false),
            ("period-growth","Period growth",KpiFormulas.Growth(curCollection,prevCollection),0,10,"%","(current CA collection - previous CA collection) / previous × 100",false,false)
        };
        return raw.Select(x => new KpiResult(x.Key,x.Name,Math.Round(x.Cur,2),Math.Round(x.Prev,2),Math.Round(x.Cur-x.Prev,2),KpiFormulas.Growth(x.Cur,x.Prev),x.Target,x.Target>0?KpiFormulas.Achievement(x.Cur,x.Target):0,KpiFormulas.Status(x.Target>0?KpiFormulas.Achievement(x.Cur,x.Target):100,x.Lower),x.Unit,[new KpiPoint(previousTo.AddDays(-1),Math.Round(x.Prev,2)),new KpiPoint(f.To.Date,Math.Round(x.Cur,2))],x.Key,x.Formula,x.Estimate)).ToList();
    }
}
